### ISSUE TITLE
Differences from other package managers

### ISSUE THREAD

**Issue by sjackman** [fishworks/gofi.sh#2]
How does Fish differ from Linuxbrew / Homebrew? http://linuxbrew.sh

Linuxbrew works on Linux, macOS, and Windows, using Windows Subsystem for Linux (WSL). Linuxbrew uses precompiled binary packages, called bottles. No need to compile from source.

**Comment by bacongobbler** [comment]
Hi @sjackman! First off, I wanted to say, as a user of Linuxbrew, thank you so much for all  your work on Linuxbrew. I also appreciate you coming to ask technical questions about the differences between Fish and Linuxbrew. :heart: 

Before I dive into what the difference is between Fish and Linuxbrew, I'll try to explain the similarities and my point of view to hopefully give you a better picture so you can draw your own ideas on what feels similar/different, as you're probably more aware of Linuxbrew's architecture than I am. Sounds fair?

Here are the parts which I feel Homebrew/Linuxbrew and Fish are very similar in design, barring the fun :tropical_fish:/:beer:  analogies (To make things easier to type, when I mention Homebrew, I am also referencing Linuxbrew. :smiley:):

1) both projects take the approach of a Tap (translation for Fish: Rigs) to represent a repository containing formulae (fish food). Both are git repositories, with the core repositories hosted on Github (Fish's core Rig is available at https://github.com/fishworks/fish-food)
2) Fish food (Formula in Homebrew-land) is a package definition written in Lua. It can be created with `gofish create <food>`. Fish food use the Lua runtime to provide simple scripting capabilities. This is necessary because Fish is primarily written in Go, and does not have its own scripting engine. Embedding Lua is a good fit here because of its simplicity compared to ecmascript 6 or other interpretive languages. Since Homebrew is written entirely in Ruby, Homebrew uses the Ruby runtime to define these packages.
3) Fish interprets Fish food during `gofish install` to retrieve information about what archives are required to fetch, verify and install a precompiled binary to /usr/local (or C:\ProgramData on Windows).

Now, when we start to drop into the semantics on what Fish fetches and installs vs. what Homebrew fetches and installs is where things start to differ: fish has no notion on the definition of how a package is compiled and distributed. In other words, there's no notion of a "bottle" or building said bottles anywhere in Fish. This is completely left up to the application developer. In fact, Fish *can* fetch bottles compiled with Homebrew to install packages, so it's compatible with Homebrew in some sense.

Now here's where my line of experience starts to lack, and I'd love your perspective on this... As an application developer coming to Homebrew, in order to create a pre-compiled binary package (a bottle) to be used across linux/macOS/WSL, one must create a Formula that fetches the package from source, compiles the binaries and then packages them into a bottle. From my understanding, this works *fantastically* IF and only if your consumers use Linuxbrew and Homebrew as their primary source for package management, and prior to WSL support for Linuxbrew, this did not support Windows developers. Because there is no support for Windows directly, users on Windows must now use a completely different tool (Chocolatey) which has its own idea on what is a package, how its installed and how application developers are required to package their application for consumption.

The problem I'm trying to solve here is: a lot of the projects I use daily (mostly all are written in Go, but not necessarily a requirement) need to release their software on Windows, Linux and MacOS, and they need to target many (if not all) of the package managers consumers use. This means that application developers need to provide packages for the following package managers:

- for Windows: NuGet packages, .msi, .zip (and more recently, .tar.gz)
- for macOS: Homebrew formulae, .pkg, .dmg, .tar.gz, .zip packages
- for Linux: Linuxbrew(Homebrew) formulae, .dep, .rpm, snap, flatpak, .tar.gz, .zip, etc. packages
- for WSL: Linuxbrew(Homebrew) formulae, .zip, .tar.gz packages

Now, when an application developer comes up to this landscape and starts considering which package format is going to

a) be the easiest to work with, and
b) have the ability to be reused across all OSes, without needing to re-tool their process around every OS's package management tool

From my point of view, It's easy to imagine why so many developer tools choose to release software in tarballs and zip archives. it's portable. :)

The main problem then comes in: the application developer has now packaged their application for every operating system they support. Now how do users consume these packages? Pre-Fish I had to

1. fetch the archive to /tmp
2. `tar xf`, `gunzip`, or `unzip` the package
3. move the binary somewhere on my $PATH

The important point to take away here is that

a) developers have devised a way to package their app for every OS
b) the user's (manual) process is identical on Windows, macOS and Linux (fetch, unzip, move to your $PATH)

This is where Fish comes in. It does not describe *how* a developer needs to package their application, and the user doesn't need to install three separate tools across all three OSes to perform the same task they'd be doing anyways. It unpacks the archive, moves it into the Barrel (translation: Cellar), and symlinks resources into /usr/local as desired. Right now there's support for bare files (as seen with [minikube](https://github.com/fishworks/fish-food/blob/aa4a134534d80f1510abbbda6fc9bd35404ff2de/Food/minikube.lua#L13)), tarballs, or zip files. I want to eventually add support to install all of the other packaging formats as well, but this is just an early proof-of-concept I was working on over the Easter holidays.

Hopefully I've covered most of the bases, but I'm always happy to answer any further questions! I think some of this discussion should definitely go on the site as a closing action item after some discussion. :)

**Comment by sjackman** [comment]
> As an application developer coming to Homebrew, in order to create a pre-compiled binary package (a bottle) to be used across linux/macOS/WSL, one must create a Formula that fetches the package from source, compiles the binaries and then packages them into a bottle.

That's not a technical requirement but a policy requirement of Homebrew/core. You could make your own tap that distributes upstream's precompiled binaries. Brewsci/bio, a tap that I maintain of bioinformatics formula, has a policy of preferring source builds, but binaries are permitted if justified (difficult to build from source). One such formula that does not build from source and intead distributes upstreams binaries is `tbl2asn`. See https://github.com/brewsci/homebrew-bio/blob/master/Formula/tbl2asn.rb#L7-L13

> Additionally, because there is no support for Windows directly, users on Windows must now use a completely different tool (Chocolatey) which has its own idea on what is a package, how its installed and how application developers are required to package their application for consumption.

I have no familiarity with Chocolatey, so I can't comment there. Linuxbrew supports Windows by using Windows Subsystem for Linux. Linuxbrew works out-of-the-box on Windows.

> And we can't add these pre-compiled archives to homebrew-core because AFAIK (I could be wrong) there's a "no blob policy" in homebrew-core, so we have to re-define how to compile our packages a second time to be used as formulae/bottles...

Homebrew/core has a no binary policy. You could create your own tap that is composed entirely of formulae that distribute upstream's precompiled binaries, if you so wished.

> Then we also come back to the problem about using three unique package managers (chocolatey, homebrew, linuxbrew) between three operating systems that perform the same tasks (fetch, unpack, install) which brings us back to square one.

Only one package manager is needed. Linuxbrew supports all three operating systems: macOS, Linux, and Windows (WSL).

**Comment by bacongobbler** [comment]
> You could make your own tap that distributes upstream's precompiled binaries.

We already do. I mentioned that previously in https://github.com/fishworks/fish/issues/41#issuecomment-380580829 and I touched on those pain points our users who use our software are experiencing. The TL;DR points were:

- the "no binary" policy in core means users need to find those taps and `brew tap` every organization that ships binaries, [which sucks](https://github.com/Azure/homebrew-draft/issues/5)
- developers that want to distribute **native** out-of-the-box Windows support (*not* WSL) need to use Chocolatey.

Look, I don't want to get into a pissing match here. All I'm saying is that the current experience and policies for the tools I use day-to-day does not match 1:1 with Homebrew/Linuxbrew. That's why I built Fish. I'm not looking to pick a fight here.

**Comment by sjackman** [comment]
I'm not aiming to pick a fight here either, Matthew. Sorry if it came across that way. I wasn't sure whether you were aware that much of your aims can be accomplished using a Homebrew tap, and doesn't necessarily require creating a new package manager. Your call in the end which way you want to go, and I'm not fussed.

> the "no binary" policy in core means users need to find those taps and brew tap every organization that ships binaries, which sucks

You need only a single tap, named for example `https://github.com/fishworks/homebrew-fish` after which `brew tap fishworks/fish` would provide all of the formulae in your tap to the end user.

> developers that want to distribute native out-of-the-box Windows support (not WSL) need to use Chocolatey.

Since you're distributing precompiled binaries, `brew install foo` could install a precompiled native `foo.exe` on Windows systems.

The package manager itself `brew` currently requires WSL to run. Porting `brew` itself to native Windows would be challenging. If you wish the package manager to run as a native Windows application, that may be justification enough for creating a new package manager.

Feel free to close this issue whenever you wish.
